Repository IntellectualSites/fastasyncvoxelsniper, pull requests merged in 2021-10, with the labels that each got.

#84 fix: Fix Stamp Brush
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/stamp/AbstractStampBrush.java
Labels: Bugfix, hacktoberfest-accepted

#85 build: Don't build non shadowed jar
  build.gradle.kts
Labels: Bugfix, hacktoberfest-accepted

#86 feat: Increase max brush size to a reasonable number
  src/main/resources/config.yml
Labels: Enhancement, hacktoberfest-accepted

#87 Update VoxelSniperConfigLoader.java
  src/main/java/com/thevoxelbox/voxelsniper/config/VoxelSniperConfigLoader.java
Labels: Enhancement
