Repository IntellectualSites/fastasyncvoxelsniper, pull requests merged in 2021-09, with the labels that each got.

#73 Add `/vs debugpaste`
  .github/ISSUE_TEMPLATE/bug_report.yml
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelSniperExecutor.java
Labels: Feature

#76 style: Do `.editorconfig` validation on compile time
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Feature

#75 ci: Add support for gh workflow deployment to the OSSRH
  .github/workflows/build.yml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Enhancement

#77 fix: Fix issues with `/b eb melt`
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/ErodeBlendBrush.java
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/ErodeBrush.java
Labels: Bugfix
