Repository IntellectualSites/fastasyncvoxelsniper, pull requests merged in 2022-06, with the labels that each got.

#164 Fix ignored y height with splatter disc brush
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/performer/splatter/SplatterDiscBrush.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelCenterExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelHeightExecutor.java
Labels: Bugfix

#165 refactor!: Update GAV to `com.intellectualsites.fastasyncvoxelsniper`
  .github/workflows/build.yml
  LICENSE
  README.md
  build.gradle.kts
  settings.gradle.kts
Labels: Breaking change

#167 feat: Use GH pages for javadocs
  .github/workflows/build.yml
  README.md
  build.gradle.kts
Labels: documentation

#170 Spiral staircase brush improvements + bug fix
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/performer/FillDownBrush.java
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/performer/ThreePointCircleBrush.java
  src/main/java/com/thevoxelbox/voxelsniper/sniper/Sniper.java
  src/main/java/com/thevoxelbox/voxelsniper/util/material/Materials.java
Labels: Feature
