Repository IntellectualSites/fastasyncvoxelsniper, pull requests merged in 2022-08, with the labels that each got.

#185 chore: Add crowdin workflow
  .github/workflows/crowdin.yml
  README.md
  crowdin.yml
Labels: chore

#187 Fixes #186
  src/main/java/com/thevoxelbox/voxelsniper/command/Command.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/BrushExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/BrushToolkitExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/DefaultExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/GotoExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/PaintExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/PerformerExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelCenterExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelChunkExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelHeightExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelInkExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelInkReplaceExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelReplaceExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelSniperExecutor.java
Labels: skip-changelog

#189 Make Stencil limits configurable
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/stencil/StencilBrush.java
  src/main/java/com/thevoxelbox/voxelsniper/config/VoxelSniperConfig.java
  src/main/java/com/thevoxelbox/voxelsniper/config/VoxelSniperConfigLoader.java
  src/main/resources/config.yml
Labels: Feature

#191 Deduplicate translation strings
  src/main/java/com/thevoxelbox/voxelsniper/util/message/VoxelSniperText.java
  src/main/resources/lang/strings.json
Labels: Bugfix
