Repository IntellectualSites/fastasyncvoxelsniper, pull requests merged in 2022-10, with the labels that each got.

#203 Release to modrinth
  .github/workflows/build.yml
  build.gradle.kts
Labels: Enhancement, hacktoberfest-accepted

#204 chore: Reword readme
  README.md
Labels: chore

#205 Sync readme with modrinth
  build.gradle.kts
Labels: hacktoberfest-accepted, chore

#202 Add option to disable update checker and set update interval
  src/main/java/com/thevoxelbox/voxelsniper/VoxelSniperPlugin.java
  src/main/java/com/thevoxelbox/voxelsniper/config/VoxelSniperConfig.java
  src/main/java/com/thevoxelbox/voxelsniper/config/VoxelSniperConfigLoader.java
  src/main/java/com/thevoxelbox/voxelsniper/listener/PlayerJoinListener.java
  src/main/resources/config.yml
Labels: Feature, hacktoberfest-accepted

#211 Setup CodeQL
  .github/workflows/codeql.yml
Labels: chore

#209 Announce changes on Discord
  .github/workflows/announce-release-on-discord.yml
Labels: hacktoberfest-accepted, chore
