Repository IntellectualSites/fastasyncvoxelsniper, pull requests merged in 2023-10, with the labels that each got.

#312 Updated the Wiki URLS
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelSniperExecutor.java
Labels: hacktoberfest-accepted

#309 Addresses issues related to maven publish scm block
  build.gradle.kts
Labels: Bugfix, hacktoberfest-accepted

#314 Replace url with uri
  src/main/java/com/thevoxelbox/voxelsniper/VoxelSniperPlugin.java
Labels: Feature, hacktoberfest-accepted

#313 Update modrinth's list of supported versions
  .github/ISSUE_TEMPLATE/bug_report.yml
  build.gradle.kts
Labels: hacktoberfest-accepted, chore

#306 Fix scanner brush height logic & typos
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/AbstractBrush.java
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/ScannerBrush.java
Labels: Bugfix

#316 Fixes #298
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Bugfix, hacktoberfest-accepted, chore

#318 [CLOUD Beta] Fix performer commands
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/AbstractPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboComboNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboComboPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboInkNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboInkPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboMaterialNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboMaterialPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ExcludeComboPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/IncludeComboPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/ink/ExcludeInkPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/ink/IncludeInkPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/ink/InkComboNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/ink/InkComboPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/ink/InkInkNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/ink/InkInkPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/ink/InkMaterialNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/ink/InkMaterialPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/ink/InkNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/ink/InkPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/material/ExcludeMaterialPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/material/IncludeMaterialPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/material/MaterialComboNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/material/MaterialComboPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/material/MaterialInkNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/material/MaterialInkPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/material/MaterialMaterialNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/material/MaterialMaterialPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/material/MaterialNoPhysicsPerformer.java
  src/main/java/com/thevoxelbox/voxelsniper/performer/type/material/MaterialPerformer.java
Labels: Bugfix

#319 [CLOUD Beta] Fix default command permission
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/DefaultExecutor.java
Labels: Bugfix
