Repository IntellectualSites/fastasyncvoxelsniper, pull requests merged in 2023-06, with the labels that each got.

#258 Upload release artifacts
  .github/workflows/upload-release-assets-.yml
Labels: chore

#257 Add support for 1.20 and sign features
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/renovate.json
  build.gradle.kts
  src/main/java/com/thevoxelbox/voxelsniper/brush/type/SignOverwriteBrush.java
  src/main/java/com/thevoxelbox/voxelsniper/config/VoxelSniperConfigLoader.java
  src/main/resources/config.yml
  src/main/resources/lang/strings.json
Labels: Feature

#260 Attempt to fix distribution tasks
  .github/workflows/build.yml
  .github/workflows/upload-release-assets-.yml
Labels: Bugfix

#265 Fix pattern parsing & some pattern outputs
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/command/executor/VoxelInkExecutor.java
  src/main/java/com/thevoxelbox/voxelsniper/sniper/snipe/message/SnipeMessenger.java
Labels: Bugfix
